name: tagpr

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - unlabeled
  workflow_dispatch:

concurrency: tagpr

jobs:
  build_and_check_before_tag:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          fetch-depth: 0
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#default --no-link
      - name: Check
        run: nix flake check -L

  tagpr:
    needs: build_and_check_before_tag
    if: |
      always() &&
      (
        (github.event_name == 'pull_request' && startsWith(github.head_ref, 'tagpr-from-')) ||
        (github.event_name != 'pull_request' && needs.build_and_check_before_tag.result == 'success')
      )
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
      issues: read
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          fetch-depth: 0
      - uses: ./.github/actions/setup-nix
      - id: tagpr
        uses: Songmu/tagpr@d1b8138b7a31075141b6cd64103de9485ced7ac9 # v1.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: tagpr
    if: needs.tagpr.outputs.tag != ''
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ needs.tagpr.outputs.tag }}
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - run: nix run nixpkgs#bun -- x changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
